# Application
spring.application.name=Login
server.address=0.0.0.0
server.port=9999

# Database
# Kavach
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false


# Logging
# logging.level.org.springframework=INFO
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Increase file upload size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

#Email Service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mail@mail.com
spring.mail.password=abcd abcd abcd abcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
